export const TEST_INCREMENT = 'TEST_INCREMENT';
export const CHANGE_MAXIMILIEN = 'CHANGE_MAXIMILIEN';

// socket
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_EMMIT = 'SOCKET_EMMIT';
